### ISSUE TITLE
Removing comments

### ISSUE THREAD

**Issue by mort3za** [craigjennings11/gulp-uglifyjs#19]
Can you add an option to remove js comments please?

**Comment by craigjennings11** [comment]
Not quite sure what you mean. Uglify by default removes comments when minifying. This option is controlled by

```js
output: {
  comments: false // default
}
```

See http://lisperator.net/uglifyjs/codegen and https://github.com/mishoo/UglifyJS2#keeping-comments-in-the-output for more info.

**Comment by mort3za** [comment]
Not sure how, but it worked with same old options.
Thanks :+1:
