### ISSUE TITLE
Fix backslashes in source-map paths on Windows

### ISSUE THREAD

**Issue by mebibou** [craigjennings11/gulp-uglifyjs#21]
Using the library on Windows shows paths in source-map as "\" instead of "/". I've checked out issues on UglifyJS2 and saw this issue: https://github.com/mishoo/UglifyJS2/pull/572

Is there a way with this library not to have the "\" when using windows?

**Comment by craigjennings11** [comment]
I like that idea. If you've already done it, a pull request is welcome.

**Comment by craigjennings11** [comment]
This plugin is no longer maintained. I recommend using [gulp-uglify](https://github.com/terinjokes/gulp-uglify) with [gulp-sourcemaps](https://github.com/floridoo/gulp-sourcemaps).
