### ISSUE TITLE
Unable to just minify files where they are

### ISSUE THREAD

**Issue by robertdunaway** [craigjennings11/gulp-uglifyjs#25]
What I want to do is minify files where they are.  This utility seems to want to force me to concatinate a group of files into a single file and then minify them.

I can see why most developers want this default behavior but for my needs this doesn't work.

I need to create minified versions of existing *.js files, rename them to *.min.js and then create a map between the original and the minified version named *.min.js.map.

I hope that makes sense.  Is this possible with gulp-uglifyjs?

Here is what I attempted and it doesn't work.

gulp.task('uglifyalljs', function () {

    return gulp.src([distFolder + '/app.js', distFolder + '/core/**/*.js', distFolder + '/apps/**/*.js', '!/**/*.min.js'])

       .pipe(uglify('*', {
           outSourceMap: true
       }))
       .pipe(uglify())
       .pipe(rename({ extname: ".min.js" }))
       .pipe(gulp.dest(distFolder + '/'));
});

I tried all kinds of variations in the first parameter of uglify so '*' is just one example.  I tried passing null and an empty string.

Any ideas?

Thanks,
Bob

**Comment by craigjennings11** [comment]
This plugin with concat all the files provided to it and the minify them, so when you pass in multiple files to `gulp.src` the plugin assumes you want to concat those files. One way to do what you are wanting is to instead create a loop that calls `uglify()` on each file. For example, something like this (rough code, may need fine-tuning):

```
gulp.task('uglifyalljs', function () {
  [distFolder + '/app.js', distFolder + '/core/**/*.js', distFolder + '/apps/**/*.js', '!/**/*.min.js'].forEach(function(pattern) {
    glob(pattern, function(err, files) {
      files.forEach(function(file)
        gulp.src(file)
          .pipe(uglify(path.basename(script, '.js') + '.min.js', {
            outSourceMap: true
          }))
          .pipe(gulp.dest(distFolder + '/'));
    });
});
```
