### ISSUE TITLE
Migration guid

### ISSUE THREAD

**Issue by TheKnarf** [craigjennings11/gulp-uglifyjs#26]
Could you write up a migration guid since this is deprecated. How would I go from using this to use `gulp-uglify` and `gulp-sourcemaps`.

**Comment by craigjennings11** [comment]
Honestly, I don't see much benefit in doing that. Both [gulp-uglify][ug] and [gulp-sourcemaps][sm] are well documented on how to use them, along with their options.

I will point out, as the note in the readme says, that you can continue to use this plugin as it works just fine, but it will not be maintained or have more features added like [gulp-uglify][ug] and [gulp-sourcemaps][sm] might.

[sm]: https://github.com/floridoo/gulp-sourcemaps
[ug]: https://github.com/terinjokes/gulp-uglify
