### ISSUE TITLE
This plugin causes wrong mapping for typescript+angular and ponts a wrong line during debug in chrome or VS

### ISSUE THREAD

**Issue by asartem** [craigjennings11/gulp-uglifyjs#30]
When I used this pluging, the wrong source map was generated and I could debug angular 2 and other typescript files. The wrong line error was caused even when debug in IE using Visual studio 2015.
Here is the sources of VS2015 test solution  with files item-list.component.ts and item.service.ts you can check.
When I disabled this lib in gulp, debug has started to work.
[bug with typescript.zip](https://github.com/craigjennings11/gulp-uglifyjs/files/737822/bug.with.typescript.zip)

**Comment by craigjennings11** [comment]
This plugin is no longer maintained. I recommend using [gulp-uglify](https://github.com/terinjokes/gulp-uglify) with [gulp-sourcemaps](https://github.com/floridoo/gulp-sourcemaps).
